### ISSUE TITLE
Crashing in lolipop and lesser with latest appcompatv7 library

### ISSUE THREAD

**Issue by bijoshtj** [freshdesk/hotline-android#19] opened 2017-05-15 05:44 UTC
Hi,

My project is integrated with hotline sdk and facebook sdk.
Recently I upgraded my facebook sdk , which requires appcompatv7 version 25+.
When i use this version of appcompat v7, hotline sdk crashes for android versions lolipop and lesser.
Trace is added below:
Reason is explained in this [link](http://stackoverflow.com/questions/35819290/invalid-drawable-tag-vector).
Looks like need a fix in hotline sdk. 

Crash Trace:

`E/AndroidRuntime( 2632): FATAL EXCEPTION: main

E/AndroidRuntime( 2632): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.testapp/com.freshdesk.hotline.activity.CategoryListActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052

E/AndroidRuntime( 2632):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)

E/AndroidRuntime( 2632):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)

E/AndroidRuntime( 2632):    at android.app.ActivityThread.access$600(ActivityThread.java:140)

E/AndroidRuntime( 2632):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)

E/AndroidRuntime( 2632):    at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime( 2632):    at android.os.Looper.loop(Looper.java:137)

E/AndroidRuntime( 2632):    at android.app.ActivityThread.main(ActivityThread.java:4895)

E/AndroidRuntime( 2632):    at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 2632):    at java.lang.reflect.Method.invoke(Method.java:511)

E/AndroidRuntime( 2632):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)

E/AndroidRuntime( 2632):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

E/AndroidRuntime( 2632):    at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime( 2632): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052

E/AndroidRuntime( 2632):    at android.content.res.Resources.loadDrawable(Resources.java:1951)

E/AndroidRuntime( 2632):    at android.content.res.Resources.getDrawable(Resources.java:672)

E/AndroidRuntime( 2632):    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)

E/AndroidRuntime( 2632):    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)

E/AndroidRuntime( 2632):    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)

E/AndroidRuntime( 2632):    at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)

E/AndroidRuntime( 2632):    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)

E/AndroidRuntime( 2632):    at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)

E/AndroidRuntime( 2632):    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)

E/AndroidRuntime( 2632):    at com.freshdesk.hotline.activity.CategoryListActivity.onCreate(Unknown Source)

E/AndroidRuntime( 2632):    at android.app.Activity.performCreate(Activity.java:5163)

E/AndroidRuntime( 2632):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)

E/AndroidRuntime( 2632):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2061)

E/AndroidRuntime( 2632):    ... 11 more

E/AndroidRuntime( 2632): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector

E/AndroidRuntime( 2632):    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)

E/AndroidRuntime( 2632):    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)

E/AndroidRuntime( 2632):    at android.content.res.Resources.loadDrawable(Resources.java:1948)

E/AndroidRuntime( 2632):    ... 30 more`

**Comment by tryprasannan** [comment] 2017-05-15 08:10
@bijoshtj Can you confirm if you are attempting to set a vector drawable for one of Hotline icons ? Hotline SDK doesn't support using vector drawables for icons. Also is this happening on any other activity ?

**Comment by bijoshtj** [comment] 2017-05-15 09:38
@tryprasannan Im not setting icons for hotline. its using default icons.
Trace says that its happening with hotline sdk (com.freshdesk.hotline.activity.CategoryListActivity.onCreate).
It happens when i trigger Hotline.showFAQs(context);

**Comment by bijoshtj** [comment] 2017-05-15 10:29
@tryprasannan  After I upgraded to appcompat v7 25,
I was getting following error for hotline, and to fix this i had to add (support-vector-drawable.jar) dependency.

W/System.err( 2477): java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
W/System.err( 2477): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:734)
W/System.err( 2477): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:367)
W/System.err( 2477): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
W/System.err( 2477): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
W/System.err( 2477): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
W/System.err( 2477): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
W/System.err( 2477): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
W/System.err( 2477): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
W/System.err( 2477): 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
W/System.err( 2477): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
W/System.err( 2477): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
W/System.err( 2477): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
W/System.err( 2477): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
W/System.err( 2477): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
W/System.err( 2477): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
W/System.err( 2477): 	at com.freshdesk.hotline.activity.CategoryListActivity.onCreate(Unknown Source)
W/System.err( 2477): 	at android.app.Activity.performCreate(Activity.java:5163)
W/System.err( 2477): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
W/System.err( 2477): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2061)
W/System.err( 2477): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)
W/System.err( 2477): 	at android.app.ActivityThread.access$600(ActivityThread.java:140)
W/System.err( 2477): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)
W/System.err( 2477): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 2477): 	at android.os.Looper.loop(Looper.java:137)
W/System.err( 2477): 	at android.app.ActivityThread.main(ActivityThread.java:4895)
W/System.err( 2477): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2477): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 2477): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
W/System.err( 2477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
W/System.err( 2477): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by tryprasannan** [comment] 2017-05-15 11:21
@bijoshtj Can you share the logs specifically following **Binary XML file line #17: invalid drawable tag vector** ?

**Comment by bijoshtj** [comment] 2017-05-15 12:50
@tryprasannan Heres the full trace:

05-15 18:21:12.851 27419-27419/com.hashcube.sqmtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hashcube.sqmtest/com.freshdesk.hotline.activity.CategoryListActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:140)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:1951)
                                                                          at android.content.res.Resources.getDrawable(Resources.java:672)
                                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                                                                          at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                                          at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
                                                                          at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
                                                                          at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                                          at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
                                                                          at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                          at com.freshdesk.hotline.activity.CategoryListActivity.onCreate(Unknown Source)
                                                                          at android.app.Activity.performCreate(Activity.java:5163)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2061)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122) 
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                          at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
                                                                          at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:1948)
                                                                          at android.content.res.Resources.getDrawable(Resources.java:672) 
                                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195) 
                                                                          at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
                                                                          at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55) 
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205) 
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
                                                                          at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519) 
                                                                          at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                                          at com.freshdesk.hotline.activity.CategoryListActivity.onCreate(Unknown Source) 
                                                                          at android.app.Activity.performCreate(Activity.java:5163) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2061) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122) 
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by bijoshtj** [comment] 2017-05-17 06:54
@tryprasannan Hi, any clue ?

**Comment by tryprasannan** [comment] 2017-05-18 18:10
@bijoshtj 
1. Any reason you're including the jar instead of an AAR for the support-vector-compat ? 
2. We tried a sample app with tagetSdkVersion 25, appcompat-v7 r25 and support-vector-compat r25 on a lollipop device and couldn't reproduce this. 
3. Have you included the following flag for vector drawbles support ?
```
android {
  defaultConfig {
    vectorDrawables.useSupportLibrary = true
  }
}
```

**Comment by bijoshtj** [comment] 2017-05-22 13:18
@tryprasannan Hi we are using ant build(we cant move out of it for now) and hence we are creating required lib projects by extracting aar files.

Similiarly we extracted support-vector-drawable.aar and using as lib project and included appcompatv7 and vector-drawable as lib projects for hotline sdk. And yes it do have vector-drawable.jar file.

Below given one of the recomendation from [stackoverflow](https://stackoverflow.com/questions/36867298/using-android-vector-drawables-on-pre-lollipop-crash) (Mayb this change in hotline mainactivity will fix?):
public class MainActivity extends AppCompatActivity {
    static {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }
}


Another issue: I was trying to integrate hotline to a test app as per android sdk documentation using android studio.
and getting error: "Failed to resolve: com.github.freshdesk:hotline-android:1.2.2"

**Comment by tryprasannan** [comment] 2017-05-22 17:32
@bijoshtj Since it's in static block & not tied to life cycle callbacks, can you try invoking setCompatVectorFromResourcesEnabled() from your application class itself ?

**Comment by bijoshtj** [comment] 2017-05-23 05:50
@tryprasannan I tried that already, which is throwing same error.

**Comment by tryprasannan** [comment] 2017-05-31 16:05
@bijoshtj Sorry for the delay. We haven't been able to reproduce this issue. Can you please share a sample project where this is reproducible ?

**Comment by chaitanya-exp** [comment] 2017-06-14 06:06
@tryprasannan facing the same issue with Hotline.showConversations().
I can be the open channel activity, but when clicked on channel to open the conversation it throws a crash.

**Comment by chaitanya-exp** [comment] 2017-06-14 06:40
@bijoshtj Did you find the solution?

**Comment by tryprasannan** [comment] 2017-06-14 17:31
@chaitanya-exp Is your issue also related to vector drawables ? If yes, can you help us with a sample project or instructions to reproduce this? We haven't been able to reproduce this (vector drawable) from our end.

**Comment by tryprasannan** [comment] 2017-06-21 14:35
@bijoshtj  Can you please share a sample project where this is reproducible ?

**Comment by tryprasannan** [comment] 2017-06-22 05:12
@bijoshtj Do note that the crash with resource not found exception is for `res/drawable/abc_vector_test.xml` which is included in support lib and not from Hotline SDK and is not referenced from within Hotline SDK either.  

Please share exact revision of appcompat and support libs you've included and the build tools version you're using in your app if you're not able to provide us with a sample project where this is reproducible

With regards to error "Failed to resolve: com.github.freshdesk:hotline-android:1.2.2", this is because the of missing maven url documented in [step 1 the integration guide](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps/)

**Comment by bijoshtj** [comment] 2017-06-22 05:49
@chaitanya-exp  nope. :(

**Comment by DvTonder** [comment] 2017-07-15 13:36
Setting the same error, same abc_vector_test.xml missing, support library 26.0.0-beta2

**Comment by tryprasannan** [comment] 2017-10-06 14:48
Closing this as its not reproducible and not enough information to debug this issue further. Please reply here or send an email to support@hotline.io if you have any further information or a sample code where this is reproducible.

**Closed as completed by tryprasannan** 2017-10-06 14:48 UTC
