### ISSUE TITLE
Hotline integration on Kindle Fire

### ISSUE THREAD

**Issue by rampr** [freshdesk/hotline-android#15] opened 2017-01-24 06:58 UTC
We see the following warning on Kindle Fire
W/HOTLINE ( 7849): Cannot proceed because the user was not created. Backlog created for message

The same build works properly on android devices. What is this error? Please let us know what should we do to fix it.

**Comment by rsquare2014** [comment] 2017-01-27 10:40
Hey! how often is this happening? we are not able to reproduce this. Is this a consistent behaviour?

**Comment by hrishikesh-p** [comment] 2017-01-27 12:51
@rampr This warning should go away on next launch. We reattempt such failures. Can you please check and let us know? 

Do mail us any additional logs you may have to support@hotline.io if the issue persists.

**Comment by rampr** [comment] 2017-01-27 12:52
Thanks! The issue went away after a few days. But will be helpful to understand what would have triggered this. Is this because of bad internet connection or some other issue ?

**Comment by hrishikesh-p** [comment] 2017-01-27 13:33
This can happen when there is a bad internet connection when the user launches the app for the first time. We retry such cases later ( when connectivity is restored or on subsequent launch when internet is available ) .

**Comment by rampr** [comment] 2017-01-30 11:51
Doesn't look like an internet issue. Saw the issue again. Seems to be happening only on Kindle devices. I saw the following logs. I can post detailed logs

`/HOTLINE_SERVICE(28062): Now Processing q
I/HOTLINE_SERVICE(28062): Now Processing e
I/HOTLINE_SERVICE(28062): Now Processing d
E/ERROR   (28062): Exception occured
E/ERROR   (28062): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/ERROR   (28062): 	at com.freshdesk.hotline.util.b.C(Unknown Source)
E/ERROR   (28062): 	at com.freshdesk.hotline.util.b.D(Unknown Source)
E/ERROR   (28062): 	at com.freshdesk.hotline.service.handler.g.a(Unknown Source)
E/ERROR   (28062): 	at com.freshdesk.hotline.service.handler.g.b(Unknown Source)
E/ERROR   (28062): 	at com.freshdesk.hotline.service.executor.b.b(Unknown Source)
E/ERROR   (28062): 	at com.freshdesk.hotline.service.HotlineService.onHandleIntent(Unknown Source)
E/ERROR   (28062): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/ERROR   (28062): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ERROR   (28062): 	at android.os.Looper.loop(Looper.java:135)
E/ERROR   (28062): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/HOTLINE_SERVICE(28062): Now Processing j
I/HOTLINE_SERVICE(28062): Now Processing v
I/HOTLINE_SERVICE(28062): Now Processing a
I/HOTLINE_SERVICE(28062): Now Processing r`

**Comment by hrishikesh-p** [comment] 2017-01-31 22:24
Hi @rampr , 

Thanks for stack trace , we will have this fixed in the next update.

**Comment by tryprasannan** [comment] 2017-02-06 07:28
@rampr This has been fixed in version [1.2.1](https://github.com/freshdesk/hotline-android/releases/tag/1.2.1). Please update and try it out.

**Closed as completed** 2017-02-09 12:18 UTC
