### ISSUE TITLE
E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/InterstitialActivity;

### ISSUE THREAD

**Issue by Naresh448** [freshdesk/hotline-android#30] opened 2017-08-04 14:50 UTC
E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/InterstitialActivity;
                                                                           at com.freshdesk.hotline.util.ar.eY(Unknown Source)
                                                                           at com.freshdesk.hotline.util.ar.eT(Unknown Source)
                                                                           at com.freshdesk.hotline.Hotline.showConversations(Unknown Source)
                                                                           at com.freshdesk.hotline.Hotline.showConversations(Unknown Source)
                                                                           at co.edgeapp.android.db.SupportService.showConversations(SupportService.java:61)
                                                                           at co.edgeapp.android.bounty.DefaultBountyActionListener.onReplyToRejection(DefaultBountyActionListener.java:144)
                                                                           at co.edgeapp.android.bounty.BountyHolder.lambda$getRejectionSnippet$15(BountyHolder.java:1176)
                                                                           at co.edgeapp.android.bounty.BountyHolder$$Lambda$18.onClick(Unknown Source)
                                                                           at android.view.View.performClick(View.java:5201)
                                                                           at android.view.View$PerformClick.run(View.java:21163)
                                                                           at android.os.Handler.handleCallback(Handler.java:746)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.freshdesk.hotline.activity.InterstitialActivity" on path: DexPathList[[zip file "/data/app/co.edgeapp.android-2/base.apk"],nativeLibraryDirectories=[/data/app/co.edgeapp.android-2/lib/arm, /data/app/co.edgeapp.android-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at com.freshdesk.hotline.util.ar.eY(Unknown Source) 
                                                                           at com.freshdesk.hotline.util.ar.eT(Unknown Source) 
                                                                           at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                                           at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                                           at co.edgeapp.android.db.SupportService.showConversations(SupportService.java:61) 
                                                                           at co.edgeapp.android.bounty.DefaultBountyActionListener.onReplyToRejection(DefaultBountyActionListener.java:144) 
                                                                           at co.edgeapp.android.bounty.BountyHolder.lambda$getRejectionSnippet$15(BountyHolder.java:1176) 
                                                                           at co.edgeapp.android.bounty.BountyHolder$$Lambda$18.onClick(Unknown Source) 
                                                                           at android.view.View.performClick(View.java:5201) 
                                                                           at android.view.View$PerformClick.run(View.java:21163) 
                                                                           at android.os.Handler.handleCallback(Handler.java:746) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                       	Suppressed: java.lang.NoClassDefFoundError: com.freshdesk.hotline.activity.InterstitialActivity
                                                                           at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                           at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                           at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                           at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                           		... 19 more
                                                                       	Suppressed: java.lang.ClassNotFoundException: com.freshdesk.hotline.activity.InterstitialActivity
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 18 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by tryprasannan** [comment] 2017-08-04 17:16
@Naresh448 Can you share more information to help us understand this better. 
1. Are you facing this on all devices or specific devices? 
2. Does this happen when the app is run from Android Studio ? Is Instant Run enabled? 
3. What is the gradle & gradle plugin version ?

**Comment by Naresh448** [comment] 2017-08-07 06:09
@tryprasannan 
1. I have tested it on nexus5x(7.1.2).
2. yes it is runned from Android Studio. Instant run is disabled.
3.  compile 'com.github.freshdesk:hotline-android:1.2.4' amd compile sdkversion is 26

**Comment by tryprasannan** [comment] 2017-08-07 06:27
@Naresh448 Thanks for this information. Can you share the specific gradle version (3.3/3.5/4.0 etc) and Android gradle plugin version (2.3.x etc) you're using ?

**Comment by Naresh448** [comment] 2017-08-07 06:36
@tryprasannan 
Gradle version: 4.0.1
Android plugin version : 2.3.3

**Comment by Naresh448** [comment] 2017-08-10 07:28
@tryprasannan  are you able to figure out why it is happening or you required more information about it please comment.

**Comment by tryprasannan** [comment] 2017-08-10 09:28
@Naresh448 It looks like there's an issue when building with Gradle 4.0, can you try with Gradle 3.5 ?

**Comment by Naresh448** [comment] 2017-08-11 15:17
@tryprasannan we have tried but its not working

**Comment by tryprasannan** [comment] 2017-08-11 15:32
@Naresh448 We're able to reproduce this issue. We think it's a build tools issue at this point. We've tried several combinations of gradle plugin & gradle versions. We'll continue investigating and share once we have an update.

**Comment by dimipaun** [comment] 2017-08-12 16:49
Hi, we're also getting this:
86 20314-20314/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: co.edgeapp.backstage, PID: 20314
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
                                                       at com.freshdesk.hotline.util.l.a(Unknown Source)
                                                       at com.freshdesk.hotline.Hotline.showConversations(Unknown Source)
                                                       at com.freshdesk.hotline.Hotline.showConversations(Unknown Source)

This is not surprising, as in the latest support packages, the ActionBarActivity has been removed:
https://stackoverflow.com/questions/29890530/actionbaractivity-is-deprecated

**Comment by tryprasannan** [comment] 2017-08-12 18:09
@dimipaun ActionBarActivity is still used to keep the SDK compatible with app's targeting older Android versions. But it can be resolved by adding a proxy class manually if you are building with support lib 26.x.x where this is removed. Create the class ActionBarActivity with the same package name as it is present in support library and extend AppCompatActivity and include this in your project and it should work.

**Comment by dimipaun** [comment] 2017-08-13 21:54
OK, but shouldn't this be handled by your SDK? I mean, this will fail with this strange error for anyone compiling with the lastest SDK, no?

**Comment by tryprasannan** [comment] 2017-08-14 03:50
@dimipaun Yes, this should ideally be handled by the SDK. What was suggested above is a temporary workaround. We're looking at ways to improve this experience.

**Comment by bhaveshopenxcell** [comment] 2017-09-07 06:08
This is really sad that not one is keen to resolve this issue at earliest. This is very very important to resolve as we just couldnt able to make our app compatible for Android Oreo just because of @hotline SDK and its really sad that they are just ignoring our comments. They should react very prompt fully with this major issue and should resolve at earliest. I doubt if I would recommend using hotline to other colleagues.

**Comment by tryprasannan** [comment] 2017-09-07 06:22
@bhaveshopenxcell We have shared a work around already for building with Oreo as Target [above](https://github.com/freshdesk/hotline-android/issues/30#issuecomment-321996954). If this still doesn't work for you, please reply here. We have documented the workaround in our[ integration guide ](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps#android8) as well

Edit: AppCompat does this same thing internally (i.e proxy ActionBarActivity to AppCompatActivity) which is exactly the workaround we have suggested above, until it was removed in 26.x.x

**Comment by tryprasannan** [comment] 2017-10-06 14:42
If this doesn't work, please reach out to us @ support@hotline.io or reopen this issue.

**Closed as completed by tryprasannan** 2017-10-06 14:42 UTC

**Comment by kshitij-sminq** [comment] 2017-10-25 13:29
I tried out your workaround on the integration guide but it did not work in my case. I have reverted to API 25 for now. 
Hotline version 1.2.5
Support library version 26.1.0
Sdk version 26
Build tools 26.0.2

**Comment by ghost** [comment] 2017-11-03 11:01
I am facing the same issue. The package solution is a VERY hacky way to fix this, considering the issue as reported in Aug, its highly disappointing that hotline is yet to fix it.
